### ISSUE TITLE
Release 2.9 missing on PyPI

### ISSUE THREAD

**Issue by mkoeppe** [Normaliz/PyNormaliz#100]
https://pypi.org/project/PyNormaliz/#history

**Comment by w-bruns** [comment]
It is indeed missing. With the next release (together with Normaliz 3.8.4) the repositories will be synchronized agin. I am waiting for Sebastian to transfer the access rights.

**Comment by w-bruns** [comment]
Now all releases are deployed automatically to PyPI.
