### ISSUE TITLE
Treatment of rational numbers

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/PyNormaliz#103]
It is not clear to me how PyNormaliz treats rational numbers. Look at the following:
```
winfried@ryzen:~/Dropbox/git_normaliz$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyNormaliz
+>>> from PyNormaliz import *
>>> C = Cone(cone = [[1/2,1],[2/7,3/4]])
---------------
1/2 1 
 2573485501354569/9007199254740992 3/4 
 
---------------
>>> 
```
The output is what Normaliz receives from PyNormaliz. I think the  strange fraction is an approximation to 2/7 and that only numbers that can be written precisely over a denominator = a power of 10 are converted precisely. The approximation looks as if it is obtained by passing through a floating point number first. This would mean that `PyFloat_Check(in) `returns true. 

In NormalizModule.cpp we find (output commands inserted by me):

```
static bool PyNumberToNmz(PyObject* in, mpq_class& out)
{
    if (PyFloat_Check(in)) {
        out = mpq_class(PyFloat_AsDouble(in));
        return true;
    }
#if PY_MAJOR_VERSION < 3
    if (PyInt_Check(in)) {
        out = PyInt_AsLong(in);
        return true;
    }
#endif
    if (PyLong_Check(in)) {
        mpz_class out_tmp;
        bool      check = PyNumberToNmz(in, out_tmp);
        if (!check) {
            return false;
        }
        out = mpq_class(out_tmp);
        return true;
    }
    if (PyList_CheckExact(in) || PyTuple_CheckExact(in)) {
        PyObject* py_num = PySequence_GetItem(in, 0);
        PyObject* py_denom = PySequence_GetItem(in, 1);
        mpz_class num;
        if (!PyNumberToNmz(py_num, num)) {
            return false;
        }
        std::cout << "Num in py: " << num << std::endl;
        mpz_class denom;
        if (!PyNumberToNmz(py_denom, denom)) {
            return false;
        }
        std::cout << "Denom in py: " << denom << std::endl;
        out = mpq_class(num, denom);
        return true;
    }
    PyObject*   in_as_string = PyObject_Str(in);
    string      s = PyUnicodeToString(in_as_string);
    int         check = out.set_str(s.c_str(), 10);
    if (check == -1) {
        throw PyNormalizInputException(
            "coefficient in matrix must be PyFloat, PyInt, PyLong, Sequence, "
            "must be able to be converted to a valid gmp input string");
    }
    return true;
}
```
I would expect that the last part of this function is used for fractions in Python 3, but the values of num and denom are not printed on cout.

If Python 2 cannot deal with fractions, then we should simply forbid them.

**Comment by w-bruns** [comment]
Is indeed considered as a float:

```
python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyNormaliz
>>> from PyNormaliz import *
>>> C = Cone(cone =[[2/7]])
Is recognized as float
2573485501354569/9007199254740992
==============
---------------
2573485501354569/9007199254740992 
 
---------------
>>> 
```

**Comment by w-bruns** [comment]
O.K. We can do it by giving a string as input: 

```
>>> C = Cone(cone = [["2/7"]]);
---------------
2/7 
 
---------------

```
This is of course goo enough, and there may be no other choice, but the present solution is misleading (and nowhere documented). This will change for sure.

**Comment by mkoeppe** [comment]
I agree that this code in PyNormaliz is problematic. It should be changed to handle Python 3 fractions directly instead of going through floats. Whether floats should be allowed at all, I am not sure. Do you allow numbers with decimals in Normaliz input files?

(Note that this does not affect Sage -- it passes rational numbers to PyNormaliz as pairs (numerator, denominator).)

**Comment by w-bruns** [comment]
Normaliz allows integers, fractions and numbers in floating point format in its input. The latter are converted precisely to fractions by the input routine, so that only fractions reach the backend.

My suggestions for PyNormaliz would be: integeres, pairs of integers or strings. The string could contain anything that is acceptable for Normaliz.

**Comment by w-bruns** [comment]
I have now inserted the use of Normaliz' own conversion of strings to mpq_class. It allows ordinary fractions as well as numbers in floating point format. 

```
   PyObject*   in_as_string = PyObject_Str(in);
    string      s = PyUnicodeToString(in_as_string);
    // int         check = out.set_str(s.c_str(), 10);
    libnormaliz::string2coeff(out,s); / <-------------- Normaliz conversion function
    int check = 0; // for the time being
    if (check == -1) {
        throw PyNormalizInputException(
            "coefficient in matrix must be PyFloat, PyInt, PyLong, Sequence, "
            "must be able to be converted to a valid gmp input string");
    }
```

Example:

```
>>> C = Cone(cone =[[1, "5.9e-1"],["2/7", [3,5] ] ])
---------------
1 59/100 
 2/7 3/5 
 
---------------
```
This ensures that PyNormaliz and Normaliz treat input numbers in the same way, except that non-integers must be enclosed in quotes for PyNormaliz. 

It may be necessary to catch exceptions thrown by the Normaliz conversion function. Will be checked added if necessary.

I would like to remove the input of Py floats since it is ambiguous in my opinion. Is this o.k. from the Sage viewpoint ?

**Comment by mkoeppe** [comment]
> I would like to remove the input of Py floats since it is ambiguous in my opinion. Is this o.k. from the Sage viewpoint ?

Yes, this is fine, we don't use floats.

**Comment by w-bruns** [comment]
It seems impossible to exclude PyFloat from the input. Formally this is now done. Nevertheless PyFloat reaches Normaliz via an implicit conversion to string on the Python side. Look at the following in which the lines starting with SSSSSS echo the string received by Normaliz:

```
>>> C = Cone(cone = [[2.0]])
SSSSSS 2.0
>>> C = Cone(cone = [[5/7]])
SSSSSS 0.7142857142857143
>>> C = Cone(cone = [[2.0ekk]])
  File "<stdin>", line 1
    C = Cone(cone = [[2.0ekk]])
                           ^
SyntaxError: invalid syntax
>>> C = Cone(cone = [["2.0ekk"]])
SSSSSS 2.0ekk
>>> C = Cone(cone = [["2.0e10"]])
SSSSSS 2.0e10
>>> C = Cone(cone = [[2.0e10]])
SSSSSS 20000000000.0
```
That Nornaliz accepts the string `2.0ekk`  is due to the fact that the function processing rational numbers reads them from a stream. So the first k ends the number and only 2.0e is converted from string to a rational number. The empty exponent is considered to be 0 (certainly questionable). If the input were from a Normaliz input file, then kk would be interpreted as the next item and cause an exception. I will insert a stricter syntax check for reading from a string.

**Comment by w-bruns** [comment]
O.K. To overcome the conversion to string, I want to check that my object is already a string.
```
NormalizModule.cpp: In function ‘bool PyNumberToNmz(PyObject*, mpq_class&)’:
NormalizModule.cpp:263:9: error: ‘PyString_Check’ was not declared in this scope
     if (PyString_Check(in)){
         ^~~~~~~~~~~~~~
NormalizModule.cpp:263:9: note: suggested alternative: ‘PyMapping_Check’
     if (PyString_Check(in)){
         ^~~~~~~~~~~~~~
         PyMapping_Check
```
Accoring to Google, PyString_Check exists, at least in Python 2. What to do in Python 3? Could not find clear instructions.
