### ISSUE TITLE
PyNormaliz does not compile with python setup.py build

### ISSUE THREAD

**Issue by robertosussex** [Normaliz/PyNormaliz#108]
I enter the PyNormaliz dir
![image](https://user-images.githubusercontent.com/37402138/110557261-28f18280-8138-11eb-97ce-ad85f7ffc3af.png)
I run python setup.py build
![image](https://user-images.githubusercontent.com/37402138/110557370-5fc79880-8138-11eb-8dc0-1538c884d7fe.png)
It gives the error
cannot open source file "libnormaliz/libnormaliz.h". This is due to the fact that some .cpp files contains lines like
 #include <libnormaliz/libnormaliz.h>
rather than
 #include <libnormaliz.h>
that would allow for standard CPATH exports etc.
Why are the routines *.cpp written with these include lines that make compilation curbersome?
Am I missing something?

Many thanks

Dr Roberto Scipioni
Research Computing Support Engineer
University of Sussex

**Comment by w-bruns** [comment]
The path` libnormaliz/libnormaliz.h` is chosen since the header files for Normaliz are stored in the directory  `$PREFIX/include/libnormaliz` by the the installation scripts. As you can see from the GitHub actions CI tests, this works very well. 

Where is your` libnormaliz.h`?

**Comment by robertosussex** [comment]
it is in
![image](https://user-images.githubusercontent.com/37402138/110652043-e79eb880-81b3-11eb-8747-d9d9a4e0f12d.png)
As you rightly mention it has to do with specifying some PATHS/PREFIXES
Should it not setup.py deal with that? With other python packages I never had this problem.
Please advice

**Comment by uvonderohe** [comment]
A simple and automatic way to install PyNormaliz is given by the install scripts in the main Normaliz directory (in your setup it should be `/its/home/rs558/TEST_SECDEC/pySecDec-1.4.5/normaliz-3.8.9/`). From there, simply run `./install_normaliz_with_eantic.sh` and `./install_pynormaliz.sh --user`. This should take care of the paths automatically. There is also updated documentation [here](https://github.com/Normaliz/PyNormaliz/blob/master/doc/PyNormaliz.pdf).

If for some reason you want to use `$CPATH` and do the installation manually, that is possible by exporting `$CPATH` as the parent directory of the `libnormaliz` directory 
(in your setup likely `/its/home/rs558/TEST_SECDEC/pySecDec-1.4.5/normaliz-3.8.9/local/include`, after running the normaliz install script as above) and also `$LIBRARY_PATH` to the `.../local/lib` directory. Then `libnormaliz/libnormaliz.h` should be found without a problem.

**Comment by robertosussex** [comment]
I have done that:

1) Loaded modules for python2

2) executed ./install_normaliz_with_eantic.sh and ./install_pynormaliz.sh

I got the error
g++ -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/NormalizModule.o -L/its/home/rs558/normaliz-3.8.9/local/lib -L/usr/lib64 -Wl,--enable-new-dtags,-R/its/home/rs558/normaliz-3.8.9/local/lib -lnormaliz -lpython3.6m -o build/lib.linux-x86_64-3.6/PyNormaliz_cpp.cpython-36m-x86_64-linux-gnu.so
/mnt/ebinstall/software/binutils/2.30-GCCcore-7.3.0/bin/ld.gold: ****error: cannot find -lpython3.6m****
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

==================

Why is it looking for Python3 ?
I have the python executable in the path. 
Is the system python interfering?
![image](https://user-images.githubusercontent.com/37402138/110686169-082c3a00-81d7-11eb-9b32-79927ee7061c.png)

Cheers


Roberto

**Comment by uvonderohe** [comment]
The script is trying to install the Python3 version since you have the executable in the path. It fails because it cannot find the corresponding Python library.
Passing `--python3 ""` as an option to the install script should prevent it from trying to build a Python3 version. Assuming you have Python2 installed, it will try to build a Python2 version. (This requires the corresponding Python2 library to succeed.)

If that does not work or you want the Python3 version, then you have to install the corresponding Python libraries. How to do this depends on your system.

The next thing you are likely to run into is an incompatibility of the current version of PyNormaliz (which the script is trying to install) with Normaliz versions prior to 3.8.10. Updating your Normaliz installation should solve this.

**Comment by robertosussex** [comment]
and that --python3 "" indeed worked.
Many thanks
Roberto

**Comment by uvonderohe** [comment]
Glad that it works.

Closing.
