### ISSUE TITLE
Unable to install - CoCoALib Configuration Fails

### ISSUE THREAD

**Issue by hridaythakkar** [Normaliz/PyNormaliz#109]
While attempting to install this library, I face an error while installing the file "./install_normaliz_with_eantic.sh"

Here is the screenshot of the error: 
![Screenshot 2021-06-01 at 5 21 17 PM](https://user-images.githubusercontent.com/85169827/120319600-d2db4800-c2fe-11eb-834e-7a1832ad47c7.png)

I'm wondering if the documentation for installing the PyNormaliz library is up to date. 

Thank you in advance!

**Comment by uvonderohe** [comment]
This seems to be a problem with CoCoA not being able to use the GMP library on your system. Please check if the file `/usr/local/lib/libgmp.a` from the error message exists and you have read permissions. If this is not the case, make sure that you have installed GMP. You might be missing a package called `libgmp-dev` or similar. Please see Section 11.1 in the manual or the CoCoA installation instructions in `nmz_opt_lib/CoCoA_source/CoCoALib-0.99710/doc/txt/INSTALL.txt`.

**Comment by hridaythakkar** [comment]
Thank you very much for your prompt response! I was able to install "./install_normaliz_with_eantic.sh" successfully. 

However, when I now  install "./install_pynormaliz.sh --user" the following error shows up: 
![Screenshot 2021-06-02 at 12 19 07 PM](https://user-images.githubusercontent.com/85169827/120437109-606d7500-c39d-11eb-89de-73d0762677bd.png)

Could you please advice how I solve this error and get PyNormaliz to successfully install?

Thank you!

**Comment by w-bruns** [comment]
I assume that you have not set any environment variables that influence the Normaliz installation, like PREFIX.
Please check whether libnormaliz.h is in the right place:

Normaliz directory/local/include

The next question is where you have put PyNormaliz. This should be in the subdirectory PyNormaliz of the Normaliz directory.

**Comment by hridaythakkar** [comment]
No, I have not set any environment variables that influence the Normaliz installation. 

libnormaliz.h was not included in "Normaliz directory/local/include" but I have done so now. Also, I've put PyNormaliz 
corectly. Please find attached two screenshots of my local folders which indicate I have done the above two steps correctly. 

![Screenshot 2021-06-02 at 3 30 51 PM](https://user-images.githubusercontent.com/85169827/120461851-0201c000-c3b8-11eb-9f99-87115fc84a3c.png)
![Screenshot 2021-06-02 at 3 31 22 PM](https://user-images.githubusercontent.com/85169827/120461863-04641a00-c3b8-11eb-9afa-3864050c1d62.png)


This still does not solve the error: 

```
"NormalizModule.cpp:19:10: fatal error: 'libnormaliz/libnormaliz.h' file not found 
#include <libnormaliz/libnormaliz.h>"
```

**Comment by uvonderohe** [comment]
There should be a directory `local/include/libnormaliz/` containing `libnormaliz.h` and several other header files which I do not see on your screenshot. This directory should be created by `./install_normaliz_with_eantic.sh` near the end. Please check again that Normaliz built successfully. You should have a file `normaliz` and e.g. running `./normaliz --version` should work. If in doubt please post the last lines of the `./install_normaliz_with_eantic.sh` output.

**Comment by hridaythakkar** [comment]
I see. Here are the last few lines of the ``./install_normaliz_with_eantic.sh`` output. I don't remember seeing an error the first time I ran it but this time, I reinstalled the Normaliz package and re-ran the file. 

![Screenshot 2021-06-02 at 4 33 30 PM](https://user-images.githubusercontent.com/85169827/120469887-8e17e580-c3c0-11eb-870b-091171864083.png)

**Comment by uvonderohe** [comment]
Please make sure that you have `libtool` installed on your system. There might also be something amiss with regards to `llvm`, so you should also check your installation of `llvm`.

**Comment by hridaythakkar** [comment]
Thanks for the tip. I've installed both libtool and llvm. Here is the error now :


![Screenshot 2021-06-02 at 5 49 20 PM](https://user-images.githubusercontent.com/85169827/120478896-f8358800-c3ca-11eb-94cd-7cfb9c3fc838.png)

**Comment by uvonderohe** [comment]
Please make sure you have `automake` installed and try again; if you are on macOS please also see Section 11.1.2 of the manual and follow the instructions given there. If the error persist, send your `build/config.log`.

**Comment by hridaythakkar** [comment]
I made sure ``automake`` is installed and tried again but no luck. I also ran the commands in Section 11.1.2 of the manual but no luck. Please find attached ``build/config.log``
[config.log](https://github.com/Normaliz/PyNormaliz/files/6584932/config.log)

**Comment by uvonderohe** [comment]
Please run `./bootstrap.sh`. Then check if the file `source/Makefile.in` exists. If it does, try again (running `./install_normaliz.sh` should be sufficient as you already installed the prerequisites).

**Comment by hridaythakkar** [comment]
It works now! Thank you so much, @uvonderohe and @w-bruns !

This may be a bit off topic but do you know how I can import the library to an environment like PyCharm? I typed 
``import PyNormaliz
from PyNormaliz import * ``  but there's an error.

**Comment by uvonderohe** [comment]
Glad to hear that it works.

I don't know how to import the library in PyCharm. If PyCharm does not automatically search for libraries in `~/.local/lib/pythonX.Y/...` then you probably have to tell it somewhere in the project settings where to find the library.

**Comment by hridaythakkar** [comment]
After installation of PyNormaliz, Is it supposed to be present in ``/local/lib/python3.9/site-packages`` ? Here is a screenshot of this directory but PyNormaliz isn't present.

![Screenshot 2021-06-03 at 5 35 04 PM](https://user-images.githubusercontent.com/85169827/120642290-55484100-c492-11eb-86bb-639819e63311.png)

**Comment by uvonderohe** [comment]
No, it should be present in your home directory `/Users/.../.local/lib/python3.9/site-packages`. Note the dot in `.local`, so it is "hidden". In a terminal you can see these files with `ls -a`.

**Comment by hridaythakkar** [comment]
Interestingly, python3.9 is not present in ``/Users/.../.local/lib/``. Here is a screenshot of this directory: 

![Screenshot 2021-06-03 at 6 03 54 PM](https://user-images.githubusercontent.com/85169827/120646129-d6a1d280-c496-11eb-92ed-945c3a23e80a.png)

**Comment by uvonderohe** [comment]
Run `./install_pynormaliz.sh --user` again (from the Normaliz directory) and look out for lines beginning with `Installed`. They should tell you the exact location of the installed library. If in doubt, post the output of that command.

After a successful PyNormaliz installation you should also be able to start an interactive Python session with `python3` and `import PyNormaliz` should not report an error.

**Comment by hridaythakkar** [comment]
When I run ``./install_pynormaliz.sh --user`` again, I receive the following error even though setuptools is installed (I checked)

![Screenshot 2021-06-03 at 7 52 36 PM](https://user-images.githubusercontent.com/85169827/120660920-72d2d600-c4a5-11eb-8a59-c6662e4ada7f.png)

**Comment by uvonderohe** [comment]
The important line is `Installed /Users/...` where it tells you the path of your PyNormaliz installation. The error message relates to a failed attempt to also create a Python2 version. You can just ignore it (unless you have a specific reason why you would want the Python2 instead of Python3 version). If the message irritates you, you can suppress the attempt passing `--python2 ""` to the installation script, i.e. `./install_pynormaliz.sh --python2 "" --user`.

**Comment by hridaythakkar** [comment]
@uvonderohe - It works now! I'm able to run commands in the IDLE software for Python. Thank you so much for your patience and help! It means a lot! 

I have a question regarding the syntax/code please: I have to do a bunch of computations on lattice polytopes such as finding the Ehrhart polynomial, volume, triangulating, f-vector, computing a unimodular simplex, convex hull, dimension, pyramids, etc. -- for these computations, is there a place for me to ask for their syntax? I read the PyNormalize tutorial for syntax on lattice polytopes but I could find only the syntax for computing the ehrhart polynomial.

**Comment by w-bruns** [comment]
There is a rather complete documentation in Appendix E of the Normaliz manual:

https://github.com/Normaliz/Normaliz/blob/master/doc/Normaliz.pdf

**Comment by hridaythakkar** [comment]
@w-bruns, Thank you for pointing me to that!

**Comment by uvonderohe** [comment]
Issue solved, closing.
