### ISSUE TITLE
Checking if P is a unimodular simplex

### ISSUE THREAD

**Issue by hridaythakkar** [Normaliz/PyNormaliz#110]
I'm studying the properties of a few classes of convex polytopes and need to check if a given polytope is a unimodular simplex. I couldn't find the code for this in the manual.

Could you please share how I can do the following:
i) Find the dimension of a polytope
ii) Check if the polytope is a unimodular simplex

I hope this is the right place to ask such a question. 
Thanks so much in advance!

**Comment by w-bruns** [comment]
Question i: The answer depends on how you define the polytope. There are two possibilities: homogeneous or inhomogeneous input. I assume that you start from a set of lattice points. I recommend "polytope" as the input type, which is homogeneous. In this way you define the C cone over your polytope and the polytope dimension is rank(C)-1.

The alternative is to use the input type "vertices" (for which you must add a coordinate equal to 1 to your lattice points). Then you can ask for the affine dimension.

Question ii: compute a triangulation. The result contains the determinants if the simplices.

**Comment by hridaythakkar** [comment]
Thank you so much @w-bruns! Apologies for the late response. Please feel free to close the issue.
