### ISSUE TITLE
constructing cone over number field from inequalities and equations

### ISSUE THREAD

**Issue by videlec** [Normaliz/PyNormaliz#114]
The cone construction over number field is confusing to me. The following does work (over the rational)
```python
>>> from PyNormaliz import NmzCone, NmzResult
>>> data = {'inequalities': [[1, -1]], 'equations': [[1, 1]]}
>>> cone = NmzCone(**data)
>>> NmzResult(cone, "Equations")
[[1, 1]]
>>> NmzResult(cone, "SupportHyperplanes")
[[1, 0]]
```
Now using the same specifications but with a number field ignores inequalities and equations
```python
>>> from PyNormaliz import NmzCone, NmzResult
>>> data = {'inequalities': [[1, -1]], 'equations': [[1, 1]]}
>>> data['number_field'] = ['a^2 - a - 1', 'a', '[1.618033988749894848 +/- 2.08e-19]']
>>> cone = NmzCone(**data)
>>> NmzResult(cone, "Equations")
[]
>>> NmzResult(cone, "SupportHyperplanes")
[]
```

**Comment by w-bruns** [comment]
It is a matter of the order in which the data are given. The number field must be first. In order to interpret the other data we must know what type of number they are.

**Comment by videlec** [comment]
I do not quite follow your answer, there is no order in keyword arguments. Note also that if you change the input to list of strings instead of list of integers it does work
```python
>>> from PyNormaliz import NmzCone, NmzResult
>>> data = {'inequalities': [['1', '-1']], 'equations': [['1', '1']]}
>>> data['number_field'] = ['a^2 - a - 1', 'a', '[1.618033988749894848 +/- 2.08e-19]']
>>> cone = NmzCone(**data)
>>> NmzResult(cone, "Equations")
[[[[1, 1], [0, 1]], [[1, 1], [0, 1]]]]
>>> NmzResult(cone, "SupportHyperplanes")
[[[[1, 1]], [[0, 1]]]]
```

**Comment by w-bruns** [comment]
Good point.  But

```
>>> data = {'number_field': ['a^2 - a - 1', 'a', '[1.618033988749894848 +/- 2.08e-19]'], 'inequalities': [[1, -1]], 'equations': [[1, 1]]}
>>> cone = NmzCone(**data)
>>> NmzResult(cone, "Equations")
[[[[1, 1]], [[1, 1]]]]
>>> NmzResult(cone, "SupportHyperplanes")
[[[[1, 1]], [[0, 1]]]]
>>> 
```
works as well. That the number field has not been ignored, is indicted by the raw format in which the results are given.

**Comment by videlec** [comment]
Also, ordering does not matter with respect to comparison
```python
>>> {1: 'one', 2: 'two'} == {2: 'two', 1: 'one'}
True
```
so that **equal** input data ends up in different results.

**Comment by w-bruns** [comment]
To be honest, I am not sure why one order works and the other doesn't and this does even depend on the number format. I put the issue on my TODO list.

The manual suggests strings for elements of number fields.

**Comment by videlec** [comment]
Thanks!

**Comment by w-bruns** [comment]
I am happy that Normaliz is useful for you!

**Comment by w-bruns** [comment]
Some comments ago you said that the order of the keyword arguments should not have an effect. I guess that this must be taken care of by the programmer and is not guaranteed by Python. Right?

**Comment by w-bruns** [comment]
I tried to reproduce the problem, but could not:
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyNormaliz
>>> from PyNormaliz import *
>>> data = {'inequalities': [[1, -1]], 'equations': [[1, 1]]}
>>> data['number_field'] = ['a^2 - a - 1', 'a', '[1.618033988749894848 +/- 2.08e-19]']
>>> cone = NmzCone(**data)
>>> NmzResult(cone, "Equations")
[[[[1, 1]], [[1, 1]]]]
>>> NmzResult(cone, "SupportHyperplanes")
[[[[1, 1]], [[0, 1]]]]

>>> 
```
Can I close the issue?
