### ISSUE TITLE
No output from PyNormaliz.NmzResult(cone,'EuclideanVolume')

### ISSUE THREAD

**Issue by jplab** [Normaliz/PyNormaliz#20]
This is a forward from the following ticket comment on the trac server of Sagemath:

https://trac.sagemath.org/ticket/25091#comment:65

In sage, I get the following error:

`sage: v = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]`
`sage: cube = Polyhedron(vertices=v,backend='normaliz')`
`sage: cube._volume_normaliz()`
`sage: cube._volume_normaliz('induced_lattice')`
`6`
`sage: cube._volume_normaliz()`
`1.0`

Equivalently, I get:

`sage: v = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]`
`sage: cube = Polyhedron(vertices=v,backend='normaliz',verbose=True)`
`# Calling PyNormaliz.NmzCone(**{'subspace': [], 'vertices': [[0, 0, 0, 1], [0, 0, 1, 1], [0, 1, 0, 1], [0, 1, 1, 1], [1, 0, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 1]], 'cone': []})`
`# ----8<---- Equivalent Normaliz input file ----8<----`
`amb_space 3`
`subspace 0`
`vertices 8`
 `0 0 0 1`
 `0 0 1 1`
 `0 1 0 1`
 `0 1 1 1`
 `1 0 0 1`
 `1 0 1 1`
 `1 1 0 1`
 `1 1 1 1`
`cone 0`
`# ----8<-------------------8<-------------------8<----`
`sage: cone = cube._normaliz_cone`
`sage: import PyNormaliz`
`sage: PyNormaliz.NmzResult(cone,'EuclideanVolume')`
`sage: PyNormaliz.NmzResult(cone,'EuclideanVolume')`
`1.0`

The first call of `EuclideanVolume` does not return anything, and the second call returns 1.0. This makes certain doctests in Sage fail.

**Comment by sebasguts** [comment]
Is this with the latest version? Will investigate . . .

**Comment by jplab** [comment]
This is with pynormaliz 1.19 and normaliz 3.6.3 .

**Comment by sebasguts** [comment]
@jplab With the latest version I made (for Normaliz 3.7) this is gone. It still needs to be released via pip.
```
>>> cone = PyNormaliz_cpp.NmzCone(**{'subspace': [], 'vertices': [[0, 0, 0, 1], [0, 0, 1, 1], [0, 1, 0, 1], [0, 1, 1, 1], [1, 0, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 1]], 'cone': []})
>>> PyNormaliz_cpp.NmzResult(cone,'EuclideanVolume')
1.0
```
I refactored the whole result method, though.

**Comment by jplab** [comment]
Alright! Which version of PyNormaliz will it be on pip?

About the result method refactoring, thanks for the heads-up, I'll make the necessary change in the sage interface.

**Comment by sebasguts** [comment]
I am still wondering about the version number. Since it now encorporates `QNormaliz`, I would probably take 2.0

**Comment by videlec** [comment]
I confirm that it works fine with the latest PyNormaliz. You should close the issue.
