### ISSUE TITLE
include_dirs/library_dirs

### ISSUE THREAD

**Issue by videlec** [Normaliz/PyNormaliz#24]
If normaliz is not installed in a standard repo, then the compiler could figure that out if `CFLAGS`/`CXXFLAGS`/`LDFLAGS` are properly set. There is no need to have the following weird logic
```
try:
    normaliz_dir = os.environ["NORMALIZ_LOCAL_DIR"]
except KeyError:
    normaliz_dir = "/usr/local"
...
                              include_dirs=[ normaliz_dir + '/include'],
                              library_dirs=[ normaliz_dir + '/lib'],
...
                              extra_link_args=['-Wl,-R' + normaliz_dir + '/lib' ],
```
Moreover, since the normaliz libraries are most likely shared libraries execution would fail anyway.

**Comment by sebasguts** [comment]
See my comment to #25. Normaliz has the possibility to use its own `local` dir. By setting the `rpath` here, the libraries in this local dir will be used.
