### ISSUE TITLE
some tests are too long

### ISSUE THREAD

**Issue by videlec** [Normaliz/PyNormaliz#30]
The test suite should test the Python interface and not Normaliz. There is no need to have lengthy tests. On my computer
- `examples/first.py` takes 2 min
- `examples/first_rational.py` takes 2min

Either there is a bug in Normaliz and this test are supposed to be faster or the example should be changed to make them run in < 10 secs.

**Comment by jplab** [comment]
You probably mean `examples/first.py` and `examples/first_rational.py`, which I believe were meant as examples and not as tests: to show that such things as computation of Hilbert series work and how. (Now I just notice apart from the second line, they seem quite equal!)

That said, this computation took 34 seconds on Winfried's computer just now. This is a computation in higher dimensional space and so, it is "normal" that it does not take 10 seconds...

**Comment by videlec** [comment]
These used to be tested in Travis script. So I would call that tests. Moreover, there is no documentation that explains what is actually going on.

**Comment by sebasguts** [comment]
We should probably exclude them from travis and add some docs, you are right.

**Comment by videlec** [comment]
Since we sort of agreed that `examples/` is dedicated to user-helpful examples, do you agree that we close this issue?
