### ISSUE TITLE
interface_error: Even entries must be matrices

### ISSUE THREAD

**Issue by mkoeppe** [Normaliz/PyNormaliz#39]
```
PyNormaliz.NmzCone(cone=[[1, 1]], subspace=[[-1, 1]], vertices=[[3, 2, 6]])
interface_error: Even entries must be matrices
```

**Comment by sebasguts** [comment]
Cannot reproduce with the latest commit. Are you sure everything got updated?

**Comment by mkoeppe** [comment]
OK...the error is triggered when the entries in vertices are actually sage rationals!
But the error message is not helpful.

**Comment by sebasguts** [comment]
I will try to get some more suitable error messages.

**Comment by sebasguts** [comment]
I added some more helpful error messages in 9329cbc953c47c4e706b5ed6276c1c038e8eb0ac
