### ISSUE TITLE
Readme do not display on PyPI

### ISSUE THREAD

**Issue by videlec** [Normaliz/PyNormaliz#54]
The [PyPI page](https://pypi.org/project/PyNormaliz/) does not display the content of the `Readme.md` file. In order to do that one must set in the `setup.py` the arguments  `long_description` and `long_description_content_type` (see [packaging documentation](https://packaging.python.org/guides/making-a-pypi-friendly-readme/)).

**Comment by sebasguts** [comment]
Solved in 9884a93f57a62c4feacf1b59fd25b44422bbd42d
