### ISSUE TITLE
Linking problem during install 

### ISSUE THREAD

**Issue by floppytree** [Normaliz/PyNormaliz#63]
I tried to install PyNormaliz 1.19 with SAGE 8.7 under Windows (with Cygwin). It failed to link, but I was able to fix that by adding ``'-lgomp', '-lgmpxx', '-lflint'`` to ``extra_link_args``.

**Comment by fingolfin** [comment]
That's a weird one. Unfortunately, there is not enough information here to debug it. How did you install PyNormaliz, exactly (i.e. what commands were entered), how was Normaliz installed, what were the precise error messages you saw?

**Comment by floppytree** [comment]
Sorry, that's too long ago. I have no more details.

**Comment by fingolfin** [comment]
OK, understandable. Sorry for the long delay :/. However, I only got involved with this project relatively recently. Anyway, I believe that in the future, we'll be able to react more quickly, so I hope you are not too much discouraged from reporting issues in the future.

Thanks!
