### ISSUE TITLE
Where is install_normaliz_with_qnormaliz_eantic.sh in normaliz-3.8.1

### ISSUE THREAD

**Issue by neilrhoffman** [Normaliz/PyNormaliz#69]
I downloaded the source code for normaliz-3.8.1 and I am trying to follow the instructions given here:
https://github.com/Normaliz/PyNormaliz/blob/master/Readme.md

I was looking for install_normaliz_with_qnormaliz_eantic.sh is it missing from the directory. 

AUTHORS				INSTALL				aclocal.m4			config.log			doc				install_normaliz_with_opt.sh	m4
CHANGELOG			Makefile.am			bootstrap.sh			config.sub			example				install_pynormaliz.sh		missing
COPYING				Makefile.in			build_static			configure			install-sh			install_scripts_opt		nmz_opt_lib
Docker				PyNormaliz			compile				configure.ac			install_normaliz.sh		local				source
Dockerfile			PyQNormaliz			config.guess			depcomp				install_normaliz_with_eantic.sh	ltmain.sh			test

This file seems to be included in version 3.6.0 downloads. But does it require brew?  ./install_normaliz_with_qnormaliz_eantic.sh: line 14: brew: command not found

**Comment by fingolfin** [comment]
Thanks for the report. The correct file is `install_normaliz_with_eantic.sh`.

Fixed in 57f69010241b3f30c87ddeeba37743127298a6a0
