### ISSUE TITLE
Travis: also test with CoCoALib

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/PyNormaliz#77]
CoCoALib is not installed with PyNormaliz on TRavis. Why not? Unclear to me.

**Comment by fingolfin** [comment]
This repository currently contains its own code to build e-antic in `.travis-install-normaliz.sh`. It first builds e-antic (if requested) and then clones and builds Normaliz. I think we should change this, to instead first clone Normaliz; then run the appropriate `install*` scripts from Normaliz; and then build Normaliz. This way, implementing support for CoCoaLib and Nauty or anything else should be relatively easy.
