### ISSUE TITLE
"Incidence" computation not accessible

### ISSUE THREAD

**Issue by jplab** [Normaliz/PyNormaliz#78]
>>> import PyNormaliz_cpp
    >>> data = {'vertices': [[1, 2, 3, 1],
    ...   [1, 3, 2, 1],
    ...   [2, 1, 3, 1],
    ...   [2, 3, 1, 1],
    ...   [3, 1, 2, 1],
    ...   [3, 2, 1, 1]],
    ...  'cone': [],
    ...  'subspace': [],
    ...  'inhom_equations': [[1, 1, 1, -6]],
    ...  'inhom_inequalities': [[-1, -1, 0, 5],
    ...   [-1, 0, 0, 3],
    ...   [0, -1, 0, 3],
    ...   [0, 1, 0, -1],
    ...   [1, 0, 0, -1],
    ...   [1, 1, 0, -3]]}
    >>> cone = PyNormaliz_cpp.NmzCone(**data)
    >>> I = PyNormaliz_cpp.NmzResult(cone, "Incidence")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    PyNormaliz_cpp.NormalizInterfaceError: This should never happen`

It should be added to the switch.

**Comment by fingolfin** [comment]
See PR #64
