### ISSUE TITLE
flint.so not found

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/PyNormaliz#83]
With

```
export CPPFLAGS="$CPPFLAGS -I$PREFIX/include"
export LDFLAGS="$LDFLAGS -L$PREFIX/lib"
```

`./install_pynormaliz.sh` works witout global installation. 

Hower `import PyNormaliz_cpp` in python3 still fails because the libraries cannot be found. It seems that the path is not forwarded to the Python module.

**Comment by fingolfin** [comment]
With PR #84, everything works for me, even without setting CPPFLAGS and LDFLAGS, as long as `--include_dirs=PREFIX...` and `--library_dirs=PREFIX...` are given

**Comment by fingolfin** [comment]
I believe this has been fixed
