### ISSUE TITLE
High level vs. low level

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/PyNormaliz#95]
There seem to be two different types of objects "Cone". Let us first produce a "high level" cone:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyNormaliz
>>> C = PyNormaliz.Cone(cone = [[1,0],[0,1]])
>>> C.HilbertBasis()
[[0, 1], [1, 0]]
>>> PyNormaliz.NmzResult(C,"FaceLattice")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PyNormaliz_cpp.NormalizInterfaceError: First argument must be a cone
```

Conversely, let us make a "low level" cone:

```
>>> D = PyNormaliz.NmzCone("cone", [[1,0],[0,1]])
>>> D.HilbertBasis()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PyCapsule' object has no attribute 'HilbertBasis'

```
The distinction between the two levels might be inevitable. And there is a way out, at least in one direction:

```
>>> PyNormaliz.NmzResult(C.cone,"FaceLattice")
[[[0, 0], 0], [[1, 0], 1], [[0, 1], 1], [[1, 1], 2]]
```

But this must be pointed out in the documentation.

**Comment by w-bruns** [comment]
The computation goals of the high level interface have now been extended. Hopefully nothing missing.

**Comment by fingolfin** [comment]
Ideally, a user should never know about or use the low-level interface. I'd not even mention it in the manual, and would suggest to also change all examples and tests to avoid it where possible (for the test suite, it may of course sometimes be necessary or desirable to directly access the low-level interface; but for examples and the documentation, it shouldn't be necessary (if any functionality is only available in the low-level interface but not the high-level interface, I'd consider that a bug).

**Comment by w-bruns** [comment]
Before the last updates, not all computation goals were reachable from high level. I agree that it can disappear from the documentation.

**Comment by w-bruns** [comment]
Low level removed from README.md.
